module.exports = {
  ref: 'refs/heads/master',
  before: '7a043ca75d80e7daac31fa25f2c648ef1f0e8384',
  after: 'a78a4fdd1216716fcbeb8929abbf320a1124956b',
  repository: {
    id: 195576075,
    node_id: 'MDEwOlJlcG9zaXRvcnkxOTU1NzYwNzU=',
    name: 'distrea',
    full_name: 'zompin/distrea',
    private: true,
    owner: {
      name: 'zompin',
      email: 'zompin@ya.ru',
      login: 'zompin',
      id: 2889906,
      node_id: 'MDQ6VXNlcjI4ODk5MDY=',
      avatar_url: 'https://avatars2.githubusercontent.com/u/2889906?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/zompin',
      html_url: 'https://github.com/zompin',
      followers_url: 'https://api.github.com/users/zompin/followers',
      following_url: 'https://api.github.com/users/zompin/following{/other_user}',
      gists_url: 'https://api.github.com/users/zompin/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/zompin/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/zompin/subscriptions',
      organizations_url: 'https://api.github.com/users/zompin/orgs',
      repos_url: 'https://api.github.com/users/zompin/repos',
      events_url: 'https://api.github.com/users/zompin/events{/privacy}',
      received_events_url: 'https://api.github.com/users/zompin/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/zompin/distrea',
    description: null,
    fork: false,
    url: 'https://github.com/zompin/distrea',
    forks_url: 'https://api.github.com/repos/zompin/distrea/forks',
    keys_url: 'https://api.github.com/repos/zompin/distrea/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/zompin/distrea/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/zompin/distrea/teams',
    hooks_url: 'https://api.github.com/repos/zompin/distrea/hooks',
    issue_events_url: 'https://api.github.com/repos/zompin/distrea/issues/events{/number}',
    events_url: 'https://api.github.com/repos/zompin/distrea/events',
    assignees_url: 'https://api.github.com/repos/zompin/distrea/assignees{/user}',
    branches_url: 'https://api.github.com/repos/zompin/distrea/branches{/branch}',
    tags_url: 'https://api.github.com/repos/zompin/distrea/tags',
    blobs_url: 'https://api.github.com/repos/zompin/distrea/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/zompin/distrea/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/zompin/distrea/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/zompin/distrea/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/zompin/distrea/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/zompin/distrea/languages',
    stargazers_url: 'https://api.github.com/repos/zompin/distrea/stargazers',
    contributors_url: 'https://api.github.com/repos/zompin/distrea/contributors',
    subscribers_url: 'https://api.github.com/repos/zompin/distrea/subscribers',
    subscription_url: 'https://api.github.com/repos/zompin/distrea/subscription',
    commits_url: 'https://api.github.com/repos/zompin/distrea/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/zompin/distrea/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/zompin/distrea/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/zompin/distrea/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/zompin/distrea/contents/{+path}',
    compare_url: 'https://api.github.com/repos/zompin/distrea/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/zompin/distrea/merges',
    archive_url: 'https://api.github.com/repos/zompin/distrea/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/zompin/distrea/downloads',
    issues_url: 'https://api.github.com/repos/zompin/distrea/issues{/number}',
    pulls_url: 'https://api.github.com/repos/zompin/distrea/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/zompin/distrea/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/zompin/distrea/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/zompin/distrea/labels{/name}',
    releases_url: 'https://api.github.com/repos/zompin/distrea/releases{/id}',
    deployments_url: 'https://api.github.com/repos/zompin/distrea/deployments',
    created_at: 1562441385,
    updated_at: '2020-02-23T19:51:24Z',
    pushed_at: 1582574857,
    git_url: 'git://github.com/zompin/distrea.git',
    ssh_url: 'git@github.com:zompin/distrea.git',
    clone_url: 'https://github.com/zompin/distrea.git',
    svn_url: 'https://github.com/zompin/distrea',
    homepage: null,
    size: 498,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 12,
    license: null,
    forks: 0,
    open_issues: 12,
    watchers: 0,
    default_branch: 'master',
    stargazers: 0,
    master_branch: 'master',
  },
  pusher: {
    name: 'zompin',
    email: 'zompin@ya.ru',
  },
  sender: {
    login: 'zompin',
    id: 2889906,
    node_id: 'MDQ6VXNlcjI4ODk5MDY=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/2889906?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zompin',
    html_url: 'https://github.com/zompin',
    followers_url: 'https://api.github.com/users/zompin/followers',
    following_url: 'https://api.github.com/users/zompin/following{/other_user}',
    gists_url: 'https://api.github.com/users/zompin/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/zompin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zompin/subscriptions',
    organizations_url: 'https://api.github.com/users/zompin/orgs',
    repos_url: 'https://api.github.com/users/zompin/repos',
    events_url: 'https://api.github.com/users/zompin/events{/privacy}',
    received_events_url: 'https://api.github.com/users/zompin/received_events',
    type: 'User',
    site_admin: false,
  },
  created: false,
  deleted: false,
  forced: false,
  base_ref: null,
  compare: 'https://github.com/zompin/distrea/compare/7a043ca75d80...a78a4fdd1216',
  commits: [
    {
      id: 'a78a4fdd1216716fcbeb8929abbf320a1124956b',
      tree_id: '0b83e1712825a630ffbaa98805c2253a7d525c16',
      distinct: true,
      message: 'commands',
      timestamp: '2020-02-24T23:07:30+03:00',
      url: 'https://github.com/zompin/distrea/commit/a78a4fdd1216716fcbeb8929abbf320a1124956b',
      author: {
        name: 'Ilya Altukhov',
        email: 'zompin@ya.ru',
        username: 'zompin',
      },
      committer: {
        name: 'Ilya Altukhov',
        email: 'zompin@ya.ru',
        username: 'zompin',
      },
      added: [
        'commands.json',
      ],
      removed: [

      ],
      modified: [

      ],
    },
  ],
  head_commit: {
    id: 'a78a4fdd1216716fcbeb8929abbf320a1124956b',
    tree_id: '0b83e1712825a630ffbaa98805c2253a7d525c16',
    distinct: true,
    message: 'commands',
    timestamp: '2020-02-24T23:07:30+03:00',
    url: 'https://github.com/zompin/distrea/commit/a78a4fdd1216716fcbeb8929abbf320a1124956b',
    author: {
      name: 'Ilya Altukhov',
      email: 'zompin@ya.ru',
      username: 'zompin',
    },
    committer: {
      name: 'Ilya Altukhov',
      email: 'zompin@ya.ru',
      username: 'zompin',
    },
    added: [
      'commands.json',
    ],
    removed: [

    ],
    modified: [

    ],
  },
};
